### ISSUE TITLE
Enable object oriented approach

### ISSUE THREAD

**Issue by pbayer** [JuliaActors/Actors.jl#14]
There are two approaches to implement behavior in the classical Actor Model:

1. **functional approach** ➔ the behavior is a partial function (currently the `:default` mode),
2. **object oriented approach** ➔ the behavior is an object (similar to the state pattern in GoF).

I follow [Akka](https://doc.akka.io/docs/akka/current/typed/actors.html) that both "styles" should be provided by modern actor systems. (Actually something similar is in `YAActL` with `state` dispatch.) Implementing that in `Actors` will further enhance its usability.

- [x] require that behavior objects are callable (as function objects),
- [x] make `onmessage`, `spawn`, `become` and `become!` work with behavior objects (type `Any`),
- [x] since functors can now directly be passed in as behaviors, restrict `f` in `Bhv` again to a `Function`,
- [x] document both styles well in `behavior.md`.

BTW: Having function objects as behaviors is much more elegant and straightforward than Akka's approach.

**Comment by pbayer** [comment]
There is an **elegant solution** to implement an object oriented approach if we define [a function object](https://en.wikipedia.org/wiki/Function_object#In_Julia) like the following:

```
mutable struct Calculator <: AbstractBehavior     # here the actor acquaintances get defined
    n::Int
    f::Function
end

(c::Calculator)() = c.n                           # here the f(c) message dependent methods
(c::Calculator)(var) = c.n = c.f(c.n, var)
function (c::Calculator)(f::F, var) where F<:Function
    c.f = f
    c(var)
end
```
with
```
julia> calc = Calculator(5, +)            # the thing is executable like a partial function
Calculator(5, +)

julia> calc(5)
10

julia> calc()
10

julia> calc(-, 5)
5

julia> calc()
5
```
Then we can do all sorts of nice things with it, e.g.

```
calc = spawn(calculator(5,+))
become!(calc, calculator(100, *))
call(calc, 100) ...
```
Isn't that beautiful? All without introducing a state mode! 

Only with introducing `AbstractBehavior` and making its instances function objects the functional approach based on a partial function `Bhv` and such function objects can be used interchangeably. We can switch seamlessly from the one to the other and back and still are compatible with the classical model.

I will change the issue accordingly and maybe I can convince @tisztamo to move that together with `Bhv` to `ActorInterfaces.Classic`.

**Comment by findmyway** [comment]
I'm wondering if inheriting from  `AbstractBehavior` is required. Sometimes we already have some objects well defined, it might be cumbersome to define a new wrapper which inherits from `AbstractBehavior`.

**Comment by pbayer** [comment]
Yes, you are right. The only strong requirement here is that the behavior is callable and there is no type check for that (only [something as here](https://github.com/JuliaLang/julia/blob/788b2c77c10c2160f4794a4d4b6b81a95a90940c/base/errorshow.jl#L256) in Base).

Maybe I was too impressed by Scala/Akka who do a lot more defensive programming. Instead if an actor cannot execute a behavior, it should fail with a `MethodError`. I prefer this to imposing too much restrictions beforehand. So I will change it. Thank you for the hint!

**Comment by tisztamo** [comment]
Yes, ActorInterfaces.Classic has no behavior type exactly for allowing easier interop with non-actor code.

Actually - if I understand the intent correctly - Classic already supports this, only with a different syntax, e.g.:

```
julia> using ActorInterfaces.Classic

julia> mutable struct Calculator
           n::Int
           f::Function
       end

julia> @ctx function Classic.onmessage(me::Calculator, msg::Number)
           println("$(me.f(me.n, msg))") # No implicit auto-reply in Classic at the time, so just print it.
       end

julia> @ctx function Classic.onmessage(me::Calculator, msg::Function)
           become(Calculator(me.n, msg))
       end
```

Running it with QuickActors.jl:

```
julia> using QuickActors, ActorInterfaces.Implementation.Tick

julia> s = QuickScheduler()
QuickScheduler(Dict{QuickAddr,Any}(), QuickActors.Envelope[])

julia> calc = Calculator(5, +)
Calculator(5, +)

julia> calcaddr = spawn!(s, calc)
QuickAddr(0xeb7654bf3286db8e)

julia> send!(s, calcaddr, 4)

julia> while Tick.tick!(s) end
9

julia> send!(s, calcaddr, *)

julia> send!(s, calcaddr, 4)

julia> while Tick.tick!(s) end
20
```

**Comment by pbayer** [comment]
> Classic already supports this, only with a different syntax

I know, but the point here is to make the object executable. There are several arguments why this is important:

1. I makes it more compatible with the classic model as behavior is an `f(c)`, "a function of the incoming communication" and it holds the "acquaintance list". Currently you need two objects for that. (Interestingly for Akka it is the same.)
2. This makes both styles, the functional and the object-oriented one interchangeable. The default such becomes simply: `onmessage(bhv, msg) = bhv(msg...)` regardless whether `bhv` is a partial function or a functor.
3. A user must not reimplement `onmessage` for behavior objects. He implements the behavior function right on the object.

Is then `onmessage` unnecessary? No! We need it to implement actor protocols and more complex behaviours around the basic/classic behavior! But this goes beyond the classical model.

Can we put this into Classic right away? Unfortunately no, since it breaks the current `@ctx` context injection method. But maybe that is solvable.

**Comment by AriMKatz** [comment]
If you ever need some tag on an object or type, but don't want to use abstract inheritance, you can always use a trait.

**Comment by tisztamo** [comment]
I agree that ActorInterfaces must support the functional style, but several points are still not clear to me:

> 1. I makes it more compatible with the classic model as behavior is an `f(c)`, "a function of the incoming communication" and it holds the "acquaintance list". Currently you need two objects for that. (Interestingly for Akka it is the same.)

The two objects are the context and the behavior? Is it possible to eliminate the context? I cannot see how. Could you please create an example where the actor calls the send, spawn and become primitives?

> 2. This makes both styles, the functional and the object-oriented one interchangeable. The default such becomes simply: onmessage(bhv, msg) = bhv(msg...) regardless whether bhv is a partial function or a functor.

When you write "partial function", you think `Func`?  `Func` is also a functor, and I think that `onmessage(bhv::Func, msg) = bhv(msg...)` is roughly how you can integrate Actors with ActorInterfaces in their current forms. (Although not clear if that works for struct messages)

So my current understanding is that you are proposing to add Func/an abstract type/trait to ActorInterfaces for this to be "standard". I agree with this, lets create an abstract type FunctionalBehavior or a trait `DispatchStyle` or something!

I still think that this should not be the only way to express actor behaviors, because I think that the two are not exactly the same semantically, and I am also in favor of the OO style. Here is an example of the difference:

```
struct Start end
struct Stop end

mutable struct Runner
    running::Bool
end

@ctx function Classic.onmessage(me::Runner, msg::Start)
    me.running = true
end

@ctx function Classic.onmessage(me::Runner, msg::Stop)
    me.running = false
end
```

In the OO style the communication is like a method call. It has a "name" (a type in our case) and optionally parameters. If the parameters are the same, the call can be still different. If I understand correctly, the type of the call is lost in the functional style, and I really do not want to lose it, because I am using it constantly in my code. But I am still not sure if I fully understand your intent here, so a bigger example would be nice.

**Comment by pbayer** [comment]
> The two objects are the context and the behavior?

No, they are the behavior object/struct and onmessage (a function to dispatch on it)

> When you write "partial function", you think Func? Func is also a functor

I think `Bhv` (I changed it to that name some weeks ago) and it is a closure.

> the two are not exactly the same

Exactly, therefore it makes sense to have both. I think with the above proposal there is no need to prefer one over the other but anyone could use the style best for his preference and for the situation. 

I find myself thinking about behavior sometimes more as an action/sequence of actions (e.g. the calculation of a factorial) and sometimes more as an object (e.g. a stack, dict or calculator). For the latter the object oriented style maybe more appropriate. The [style guide in Akka](https://doc.akka.io/docs/akka/current/typed/style-guide.html) has more about similarities and differences. But for them the differences seem to be much bigger than for us with the above proposal.

**Comment by pbayer** [comment]
> In the OO style the communication is like a method call. It has a "name" (a type in our case) and optionally parameters. If the parameters are the same, the call can be still different.

What do you mean by a different call? If we have `f(a, c)` with `f`: behavior function, `a`: acquaintance and `c`: communication, then if the types of `a` and `c` remain the same, the call is the same but the result can vary according to the values of `a` and `c`. If `a` or `c` or both change type, the call changes. Right?

**Comment by tisztamo** [comment]
Could you please create your proposal in ActorInterfaces.jl? I have tried to create an issue there for it, but I just found that I really do not understand what you are proposing. It seems to me that you are thinking in Actors.jl terms and semantics which I do not know, and I have the feeling that your understanding of ActorInterfaces.jl is different than mine.

For example, the `Classic.send` primitive currently only accepts a single object as the message, but your original example here dispatches to several methods with different number of arguments. Maybe we have to extend the semantics of `send` to support this. But how will `onmessage` behave then? And why do we still need `onmessage` when the message is dispatched to the call on the behavior functor? In my understanding the important difference is not the name of the function  where the message gets dispatched, it can be either `onmessage` or the functor's call, but how the message is passed.

So please propose something concrete in ActorInterfaces.jl which we can implement in QuickActors.jl to see how it works.

Thank you very much!

**Comment by pbayer** [comment]
no worry! This may take a little while since I'm working on `Actors` now. In the meantime you can look at [the new behavior docs](https://juliaactors.github.io/Actors.jl/dev/behaviors/) there to see what I'm talking about.

> your original example here dispatches to several methods with different number of arguments

I have no idea what you are talking about. Which example, what arguments? Can you please help me?

> why do we still need `onmessage` when the message is dispatched to call the behavior functor

I explained that above. Strictly speaking `onmessage` must not be in `Classic` since the classical model is all about behavior which - as we have seen - can be put in a closure or a functor. 

1. But with `onmessage` you can realize more complex behaviours (Armstrong's British English here!) beyond the classical model required for fault tolerance, supervisors, genservers and the like. It is useful to realize the actor machinery, a.k.a. a finite state machine.
2. For different actor implementations `onmessage` can be the common glue or basic entry point: They may send and deliver messages differently but then they activate the actor with `onmessage`.

Therefore I suggest to let it there.

**Comment by pbayer** [comment]
## Register Actors v0.1.8

@JuliaRegistrator register

Release notes:

- **object-oriented style**: any callable object can be given as behavior
- functional (as before) and object-oriented style are equivalent
