### ISSUE TITLE
Any plan to update this package?

### ISSUE THREAD

**Issue by findmyway** [JuliaActors/Actors.jl#3]
I've searched around and only find this package to support Actor model. I'm curious if there's any plan to update this package?

**Comment by oschulz** [comment]
I'll definitely try to make this package compatible with Julia v0.7/v1.0. As for significant improvements/extensions, I'm not quite sure when and how. Ideas are very welcome, of course.

**Comment by oschulz** [comment]
It looks like Julia multithreading will become much more powerful in the future (asynchronous threads, etc.). Based on that Actors.jl could become much more powerful, but I guess we'll need to be a bit patient.

**Comment by findmyway** [comment]
Cool
Once you feel it is the time to update, I would be glad to help.

**Comment by oschulz** [comment]
Thanks, help will be very welcome. We may have to be a bit patient, but I hope the new multi-threading API will come with Julia v1.1.

**Comment by pbayer** [comment]
Hello, we are currently rewriting this package based on the classical Actor model and work done already in YAActL.jl. The roadmap is roughly outlined [on Discourse](https://discourse.julialang.org/t/juliaactors-a-road-to-an-actors-ecosystem/49898).

**Comment by pbayer** [comment]
Actors v0.1.1 is available from the Julia registry.

I will follow further the roadmap.

**Comment by pbayer** [comment]
roadmap for development in the next weeks is described in issues #8, #9 and #10 .
I close this now.
