### ISSUE TITLE
Register rewritten Actors v0.1.1

### ISSUE THREAD

**Issue by pbayer** [JuliaActors/Actors.jl#6]
Actors v0.1.1 must provide a working implementation of the basic **classical Actor Model** as described [in the roadmap](https://discourse.julialang.org/t/juliaactors-a-road-to-an-actors-ecosystem/49898) and an **interface to other Julia actor packages** to enable them to use the API and ecosystem.

- [x] rewrite package,
- [x] setup CI,
- [x] Agha’s examples running,
- [x] test coverage for functionality,
- [x] test interface with `SlowActors.jl`,
- [x] basic documentation,
- [x] register

**Comment by pbayer** [comment]
documentation added

**Comment by pbayer** [comment]
@JuliaRegistrator register

**Comment by pbayer** [comment]
Again after [PR](https://github.com/JuliaRegistries/General/pull/24754/checks?check_run_id=1407735828) was merged.

@JuliaRegistrator register

**Comment by pbayer** [comment]
Actors v0.1.1 is available from the Julia registry

**Comment by oschulz** [comment]
Congrats!
